library(shiny)
library(imola)
library(dplyr)
library(tidytext)
library(SnowballC)
library(tidyverse)
library(tidytext)
library(tm)
library(textcat)
library(fastText)
library(wordcloud)
library(wordcloud2)
library(leaflet)
library(shinythemes)
data<-read.csv("expand.csv")
review<-read.csv("review_cleaned.csv")

  